name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate changelog snippet
        id: changelog
        run: |
          echo "## Mudanças\n" > RELEASE_NOTES.md
          git log --pretty=format:'- %s' $(git describe --tags --abbrev=0 --tags --match "v*" 2>/dev/null)..HEAD >> RELEASE_NOTES.md || true
          cat RELEASE_NOTES.md

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          body_path: RELEASE_NOTES.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
